provider:
  name: faas
  gateway: http://127.0.0.1:8080
  network: func_functions

functions:
  basic-auth:
    lang: golang-http
    handler: ./basic-auth
    image: alexellis2/basic-auth:0.1
    secrets:
     - fn-basic-auth-username
     - fn-basic-auth-password
